apiVersion: v1
kind: ConfigMap
metadata:
  name: guardian-config
  namespace: {{ include "kube-image-guardian.namespace" . }}
data:
  config.yaml: |-
    {{- .Values.guardianConfig | toYaml | nindent 4 }}
