apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-image-guardian.fullname" . }}-webhook
  namespace: {{ include "kube-image-guardian.namespace" . }}
  labels:
    {{- include "kube-image-guardian.labels" . | nindent 4 }}
spec:
  type: {{ .Values.networkConfig.service.type }}
  ports:
    - port: {{ .Values.networkConfig.service.port }}
      targetPort: {{ .Values.networkConfig.appPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "kube-image-guardian.selectorLabels" . | nindent 4 }}
